---
title: "Aggression regression"
output: html_document
---

AGGRESSION REGRESSION- run regressions predicting the daily mean of head temp, rather than one value for each site
```{r}
#subset data I actually need
atak <- select(dogg, Site, shed, Value, rnd.dates, d.mean, d.min, d.max, UAA..ft2., elev.mean, slope.mean, head.temp, head.dmean, airT, air.d.mean, air.d.min, air.d.max)%>%
  mutate(date = date(rnd.dates))
atak$rnd.dates <- ymd_hms(atak$rnd.dates)

#lm calculating one avg head temp value
h.avg.model <- lm(head.dmean ~ 
                slope.mean  +
                elev.mean + 
                UAA..ft2.,data = dogg)
summary(h.avg.model)
hair.avg.model <- lm(head.dmean ~ 
                slope.mean  +
                elev.mean + 
                UAA..ft2. +
                air.d.mean  ,data = dogg)
summary(hair.avg.model)

modeltester <- dogg%>%
  select(Site, shed, slope.mean, elev.mean, AREA, UAA..ft2., head.temp)%>%
  mutate(h.avg.model = 1.261e-01 * slope.mean + 
  -6.722e-04 * elev.mean + 
   5.125e-06 * UAA..ft2.+
   8.329e+00)%>%
  group_by(Site)%>%
  mutate(avg.head = mean(head.temp, na.rm = TRUE))
```

```{r}
#calculate lm for each day at each site
atak.day <- select(atak, -c(rnd.dates, Value, head.temp, airT))
atak.day <- unique(atak.day)
atak.day <- atak.day[complete.cases(atak.day),]

dayz <- select(atak.day, date)
dayz <- unique(dayz)

for(k in 1:length(dayz$date)){
  day <- dayz$date[k]
  df <- filter(atak.day, date == day)
  reg <- lm(head.dmean ~ air.d.mean + UAA..ft2. + elev.mean + slope.mean,
            data = df)
  r2 <- summary(reg)$r.squared
  co <- coefficients(reg)
  #output
  temp <- mutate(df, r2 = r2, co.int = co[1], 
                              co.air.dmean = co[2],
                              co.UAA = co[3],
                              co.elev = co[4],
                              co.slope = co[5])
  if(k == 1) alldat <- temp
  if(k > 1) alldat <- rbind(alldat, temp)
}

prediction <- mutate(alldat, pred = co.int + air.d.mean * co.air.dmean + co.UAA * UAA..ft2.+
                     co.elev * elev.mean + co.slope * slope.mean)
ggplot(prediction, aes(x = pred,
                       y = head.dmean))+
  geom_point(aes(color = shed))+
  geom_abline(slope = 1, intercept = 0)+
  xlim(9, 14)+
  ylim(9, 14)+
  theme_classic()

atakr.day <- alldat
ggplot(atakr.day, aes(x = date, y = r2))+
  geom_point()+
  theme_classic()
```
Just calculated for days


Calculate r2 for predicting every hour
```{r}
#calculate lm for each day at each site
atak.hour <- atak
atak.hour$hour <- floor_date(atak$rnd.dates, unit = "hour")
atak.hour <- atak.hour%>%
  group_by(hour, Site)%>%
  mutate(head.hmean = mean(head.temp), air.hmean = mean(airT))%>%
  select(Site, shed, hour, head.hmean, air.hmean, UAA..ft2., elev.mean, slope.mean)

atak.hour <- unique(atak.hour)
atak.hour <- atak.hour[complete.cases(atak.hour),]
atak.hour <- as.data.frame(atak.hour)

hourz <- select(atak.hour, hour)
hourz <- unique(hourz)

for(o in 1:length(hourz$hour)){
  our <- hourz$hour[o]
  df <- filter(atak.hour, hour == our)
  reg <- lm(head.hmean ~ air.hmean + UAA..ft2. + elev.mean + slope.mean,
            data = df)
  r2 <- summary(reg)$r.squared
  co <- coefficients(reg)
  #output
  temp <- mutate(df, r2 = r2, co.int = co[1], 
                              co.air.hmean = co[2],
                              co.UAA = co[3],
                              co.elev = co[4],
                              co.slope = co[5])
  if(o == 1) alldat <- temp
  if(o > 1) alldat <- rbind(alldat, temp)
}

prediction.hour <- mutate(alldat, pred = co.int + air.hmean * co.air.hmean + co.UAA * UAA..ft2.+
                     co.elev * elev.mean + co.slope * slope.mean)
ggplot(prediction.hour, aes(x = pred,
                       y = head.hmean))+
  geom_point(aes(color = shed))+
    geom_abline(slope = 1, intercept = 0)+

  theme_classic()
#looking at just mull creek predictions
pred.mul <- filter(prediction.hour, shed == "MUL")
ggplot(pred.mul, aes(x = pred,
                       y = head.hmean))+
  geom_point(aes(color = Site))+
    geom_abline(slope = 1, intercept = 0)+
  theme_classic()
#look at just ULB to find the shed that is poorly predicted
pred.ulb <- filter(prediction.hour, shed == "ULB")
ggplot(pred.ulb, aes(x = pred,
                       y = head.hmean))+
  geom_point(aes(color = Site))+
    geom_abline(slope = 1, intercept = 0)+
  theme_classic()

elm.mul <- filter(elm, shed == "MUL")
ggplot(elm.mul, aes(x = element,
                    y = measurement))+
  geom_point(aes(color = site))+
  theme_classic()

atakr.hour <- alldat
ggplot(atakr.hour, aes(x = hour, y = r2))+
  geom_point()+
  theme_classic()

gour <- atakr.hour%>%
  select(Site, shed, hour, head.hmean, air.hmean, r2)
```


Calculate r2 at different time scales using the time every ten minutes
```{r}
#calculate lm for each 10 min interval at each site
atak.min <- unique(atak)
atak.min <- atak.min[complete.cases(atak.min),]

minz <- select(atak.min, rnd.dates)
minz <- unique(minz)

for(o in 1:length(minz$rnd.dates)){
  mint <- minz$rnd.dates[o]
  df <- filter(atak.min, rnd.dates == mint)
  reg <- lm(head.temp ~ airT + UAA..ft2. + elev.mean + slope.mean,
            data = df)
  r2 <- summary(reg)$r.squared
  co <- coefficients(reg)
  #output
  temp <- mutate(df, r2 = r2, co.int = co[1], 
                              co.airT = co[2],
                              co.UAA = co[3],
                              co.elev = co[4],
                              co.slope = co[5])
  if(o == 1) alldat <- temp
  if(o > 1) alldat <- rbind(alldat, temp)
}

prediction.min <- mutate(alldat, pred = co.int + airT * co.airT + co.UAA * UAA..ft2.+
                     co.elev * elev.mean + co.slope * slope.mean)
ggplot(prediction.min, aes(x = pred,
                       y = head.temp))+
  geom_point(aes(color = shed))+
      geom_abline(slope = 1, intercept = 0)+
  theme_classic()

atakr.min <- alldat
mast <- atakr.min%>%
  rename(r2.minpmin = r2) #minpmin- min pred by actual measurements, 10 min inc values
mast$hour <- floor_date(mast$rnd.dates, unit = "hour")


mast <- left_join(mast, gour, by = c("Site", "shed", "hour"))%>% #hour pred by hmean
  rename(r2.hourphour = r2)

gai <- select(atakr.day, Site, shed, date, r2)
mast <- left_join(mast, gai,  by = c("Site", "shed", "date"))%>% #day pred by dmean
  rename(r2.daypday = r2)

#Calculate
#day pred by min
#hour pred by min
for(o in 1:length(minz$rnd.dates)){
  mint <- mast$rnd.dates[o]
  df <- filter(mast, rnd.dates == mint)
  reg <- lm(head.dmean ~ airT + UAA..ft2. + elev.mean + slope.mean,
            data = df)
  reg2 <- lm(head.hmean ~ airT + UAA..ft2. + elev.mean + slope.mean,
            data = df)
  r2 <- summary(reg)$r.squared
  r2.2 <- summary(reg2)$r.squared
  #output
  temp <- mutate(df, daypmin = r2, hourpmin = r2.2)
  if(o == 1) alldat <- temp
  if(o > 1) alldat <- rbind(alldat, temp)
}

hup <- select(alldat, Site, shed, rnd.dates, daypmin, hourpmin)
mast <- left_join(mast, hup, by = c("Site", "shed", "rnd.dates"))%>%
  rename(r2.daypmin = daypmin, r2.hourpmin = hourpmin)

masty <- unique(mast)
hasty <- select(masty, rnd.dates, r2.daypday, r2.hourphour, r2.minpmin)%>%
  gather(key = "r2.type", value = "value", -rnd.dates)

hasty$r2.type <- factor(hasty$r2.type)
hasty$r2.type <- factor(hasty$r2.type, levels = c("r2.minpmin","r2.daypday", "r2.hourphour"))
hasty <- unique(hasty)

p <-ggplot(hasty, aes(x = rnd.dates,
                      y = value))+
  geom_boxplot(aes(color = r2.type))+
  theme_classic()
p  
#xlim("2019-07-02 12:00:00 UTC", "2019-07-06 12:00:00 UTC")
```

Do the regresssions again, but use NOAA airT from GG and elsewhere
```{r}
grog <- read.csv("Tempsanddata_11_8.csv")
grop <- grog %>%
  mutate(date = date(rnd.dates)) %>%
  select(Site, shed, date, d.mean, UAA..ft2., slope.mean, elev.mean, head.dmean, air.d.mean, air.d.min, air.d.max)

grop <- unique(grop)


scully <- read.csv("Cullowheerain.csv")
scully$DATE <- ymd(cull$DATE)
#subsetting the time frame of interest
start <- which(scully$DATE == mdy("6-13-19"))
end <- which(scully$DATE == mdy("7-8-19"))
noat <- scully[start:end,]
# use this and TMIN and TMAX instead of avgs used in previous regs
#join the topometrics and temps to NOAA data

noap <- noat%>%
  rename(date = DATE)

noap$TMAX <- as.double(noap$TMAX)
noap$TMIN <- as.double(noap$TMIN)

noap <- select(noap, date, TMAX, TMIN, TOBS)

noak <- left_join(grop, noap, by = "date")
#noak <- noak[complete.cases(noak),]
#formatted data for calculations
```

```{r}
#time to calc r2 and coeff for dmean, hmean, and every ten minutes using NOAA data
#making minutes df
minz <- select(noak, rnd.dates)
minz <- unique(minz)



noak$hour <- noak$rnd.dates
noak$hour <- floor_date(noak$rnd.dates, unit = "hour")
noak <- noak%>%
  group_by(hour, Site)%>%
  mutate(head.hmean = mean(head.temp), air.hmean = mean(airT))

noak <- unique(noak)
noak <- as.data.frame(noak)

hourz <- select(noak, hour)
hourz <- unique(hourz)

noak$TMAX <- as.double(noak$TMAX)
noak$TMIN <- as.double(noak$TMIN)
for(o in 1:length(minz$rnd.dates)){
  mint <- minz$rnd.dates[o]
  df <- filter(noak, rnd.dates == mint)
  reg <- lm(head.temp ~ TMIN + TMAX + UAA..ft2. + elev.mean + slope.mean,
            data = df)
  r2 <- summary(reg)$r.squared
  co <- coefficients(reg)
  #output
  temp <- mutate(df, r2 = r2, co.int = co[1], 
                              co.tmin = co[2],
                              co.tmax = co[3],
                              co.UAA = co[4],
                              co.elev = co[5],
                              co.slope = co[6])
  if(o == 1) alldat <- temp
  if(o > 1) alldat <- rbind(alldat, temp)
}

noak <- left_join(noak, alldat, by = )

for(k in 1:length(dayz$date)){
  day <- dayz$date[k]
  df <- filter(noak, date == day)%>%
    select(-Value, -rnd.dates, -head.temp, -airT, - hour, -head.hmean, -air.hmean)
  df <- unique(df)
  reg <- lm(head.dmean ~  TMIN  
            + UAA..ft2.
            + elev.mean 
            + slope.mean,
            data = df)
  r2 <- summary(reg)$r.squared
  co <- coefficients(reg)
  #output
  temp <- mutate(df, r2 = r2, co.int = co[1], 
                              co.tmin = co[2],
                              co.UAA = co[4],
                              co.elev = co[5],
                              co.slope = co[6])
  if(k == 1) alldat <- temp
  if(k > 1) alldat <- rbind(alldat, temp)
}

test <- select(noak, UAA..ft2., elev.mean, head.dmean, TMAX, TMIN, TOBS)
unique(test)
plot(test)
```

```{r}

brus <- select(brush, site, shed, Value, rnd.dates, d.mean, airT, air.d.mean)
#trip has some good stuff
head(trip)

summary(lm(head.dmean))


dayz <- select(noak, date)
dayz <- unique(dayz)

noak.ulb <- filter(noak, shed %in% c("ULB", "GG"))

ggplot(noak, aes(x = air.d.mean))+
  geom_line(aes(y = TMAX, color = shed))+
  geom_line(aes(y = TMIN, color = shed))+
  theme_classic()

for(k in 1:length(dayz$date)){
  day <- dayz$date[k]
  df <- filter(noak.rmo, date == day)
  reg <- lm(head.dmean ~  TMIN  
            + UAA..ft2.
            + elev.mean 
            + slope.mean,
            data = df)
  r2 <- summary(reg)$r.squared
  co <- coefficients(reg)
  #output
  temp <- mutate(df, r2 = r2, co.int = co[1], 
                              co.tmin = co[2],
                              co.UAA = co[4],
                              co.elev = co[5],
                              co.slope = co[6])
  if(k == 1) alldat <- temp
  if(k > 1) alldat <- rbind(alldat, temp)
}

```

