---
title: "cold calibration attempt 8_22"
output: pdf_document
---
8/22  
Christa wanted to see the calibration data, I am going to try to work it up real quick.  
I am going to adapt the code from TempFormatting 7_10.Rmd in order to read in the data and format it in a way that I can use.

8/27 
Resumed working on compiling this data for Christa
```{r}
#Packages
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggridges)
library(lubridate)
library(SAVER)
```

Deleted 5, 15, and set 144 and 137 to NA
```{r}
#read in all the csv files
#removed 15- ULB4HB- super messed up, sensor was broken
files <- list.files(path = "Ibutton calibration data 6_4_19/")
sites <- read.csv("site_temps_7_11.csv", header = T, sep = ",")

for (y in 2:length(files)) {
    data <- read.csv(paste0("Ibutton calibration data 6_4_19/", files[y]), 
                     skip = 19, 
                     header = T, sep = ",")
    data$fdates <- mdy_hms(data$Date.Time)
    data$rnd.dates <- round_date(data$fdates, unit = "minute")
    data$sensor <- files[y]
    #data$sensor <- gsub("data","\\1", data$sensor)
    data$sensor <- gsub(".csv","\\1", data$sensor)
    if(y == 2)alldat <- data
    if(y > 2)alldat <- rbind(alldat, data)
}

cal <- select(alldat, rnd.dates, Value, sensor)
#cal$Value[which(cal$sensor == c("144", "137", "5"))] <- NA

start <- mdy_hm("6-04-19 17:30")
end <- mdy_hm("6-04-19 18:00")
cal <- filter(cal, rnd.dates >= start)
cal <- filter(cal, rnd.dates <= end)

raw <- ggplot(data = cal)+
  geom_line(aes(x = rnd.dates, y = Value,
                color = sensor))
#adding thermometer readings
cal.spread <- cal %>% spread(sensor, value = Value)
cal.spread$control <- c(0.1,0.2,0.1,0.2,0.2,0.2,0.2,0.3,0.2,0.2,
                        0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,
                        0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.3)
cal.tall <- cal.spread %>% gather(sensor, Value, -rnd.dates)

#creating a column of the diff between the control and every number
cal2 <- cal.tall %>% group_by(sensor) %>% mutate(Value - 0.2)
#saving data as csv
#write.csv(master.mean, file = "temps.means.csv")
```


Format the data to work with- from summer deployment code
```{r}
#formatting data to remove undeployed sensors

#finding ones that weren't deployed
data.sensors <- unique(alldat$sensor)
sites.sensors <- unique(sites$sensor)
diff <- setdiff(data.sensors, sites.sensors)
#removing sensors that weren't deployed
alldat <- filter(alldat, sensor %in% sites$sensor)
#add site location column
alldat$sensor <- as.numeric(alldat$sensor)
#removed sensor 54- something wrong
#alldat2 <- filter(alldat, sensor != 54)
#adding sites data sheet- matching sensors with sites
alldat2 <- inner_join(alldat, sites, by = "sensor")
#identify list of sites
locs <- unique(alldat2$site)

#formatting time to beginning and end of deployment period
start <- mdy_hm("6-13-19 13:10")
end <- mdy_hm("7-8-19 11:20")
alldat3 <- filter(alldat2, rnd.dates >= start)
alldat3 <- filter(alldat3, rnd.dates <= end)

master <- select(alldat3, Value, sensor, rnd.dates, site, type, shed)
#replacing wacky temps with NA
which(master$Value == -41, arr.ind = T)
master$Value[74005] <- NA
master$Value[which(master$Value > 35, arr.ind = T)] <- NA
#setting everything below 0 = NA, it didn't get below 0
master$Value[which(master$Value < 0, arr.ind = T)] <- NA
#remove LS180A and W600A

master$rnd.dates <- as.POSIXct(master$rnd.dates, format = "%Y-%M-%d %H:%M:%S")

#write.csv(master, file = "Formatted.temps.tall_7_17.csv")
```