---
title: "Figure set 10_3"
output: html_document
---
10/4
Make plots with topo metrics, make final figure set to send to JP

```{r global_options, include=FALSE}
#global settings
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r}
#Packages
library(tidyverse)
library(lubridate)
library(ggridges)
```

```{r}
#read in data
topo <- read.csv("topodata 10_4.csv")
topo.og <- read.csv("topodata 10_4.csv")

temps <- read.csv("Tempswithdmetrics10_3.csv")
#format time and other stuff
temps$rnd.dates <- ymd_hms(temps$rnd.dates)
temps <- temps %>% mutate_each(list(as.factor), sensor)
temps <- temps %>% mutate_each(list(as.character), site, type, shed)
topo <- topo %>% mutate_each(list(as.character), Site, type, Shed)

#change some of the col names and how I have the sites named
#remove airT
temps.water <- filter(temps, type != "air")
temps.water$site <- gsub('.{2}$', '', temps.water$site)
temps.water <- temps.water %>%
  mutate(type = replace(type, type != "head", "Downstream"),
         type = replace(type, type == "head", "Head"),
         site = replace(site, site == c("W60", "W40", "GC30", "GC10", "LS18", "LS"),
                              c("W600", "W400", "GC300", "GC100", "LS180", "LS0")))
temps.water <- temps.water %>%
  mutate(type = replace(type, type == "head", "Head"))
topo <- topo %>%
  mutate(type = replace(type, type == "Down", "Downstream"))

#selecting sites, renaming one of the columns in the same function
topo <- topo %>% 
  select(Site, type, Slope..percent.rise., Elevation..ft., UAA..ft2.) %>% 
  rename(site = Site)
#combine the datasets by Site and type
comb <- left_join(temps.water, topo, by = c("site", "type"))
```
  
```{r}
test <- select(comb, site, type, Elevation..ft.)
test <- distinct(test)

as_tibble() %>% distinct() %>% select(temps, site)
select(temps, site, type, A.B) %>% distinct() %>% as_tibble()

###SUPER USEFUL
select(temps.water, site, type, A.B) %>% distinct()

```


```{r}
#I need to make a data sheet that has one sensor per site
#in order to pull of the plots I want to make
temps <- read.csv("Tempswithdmetrics10_3.csv")
topo <- read.csv("topodata 10_4.csv")

#format time and other stuff
temps$rnd.dates <- ymd_hms(temps$rnd.dates)
temps <- temps %>% mutate_each(list(as.factor), sensor)
temps <- temps %>% mutate_each(list(as.character), site, type, shed)

temps.water <- filter(temps, type != "air")

temps.water <- filter(temps.water, site %in% c("ULB2HA", "ULB2CB","ULB3HA", "ULB3CB", "ULB4HA", "ULB4CA", "RMO1HA", "RMO1CB", "RMO2HA", "RMO2CB", "RMO3HB", "RMO3CB","MUL2HA", "MUL2CB", "MUL4HB", "MUL4CA", "MUL7HB", "MUL7CA","W600B", "W400A", "GC300B","GC100B", "LS180B", "LS0B"))

temps.water$site <- gsub('.{2}$', '', temps.water$site)

temps.water <- temps.water %>%
  mutate(type = replace(type, type == "channel", "Downstream"),
         type = replace(type, type == "head", "Head"),
         site = replace(site, site == "W60", "Wind"),
         site = replace(site, site == "W40", "Wind"),
         site = replace(site, site == "GC10", "Glac"),
         site = replace(site, site == "GC30", "Glac"),
         site = replace(site, site == "LS", "Land"),
         site = replace(site, site == "LS18", "Land"))

topo <- topo %>% mutate_each(list(as.character), Site, type, Shed)
topo <- topo %>% 
  select(Site, type, Slope..percent.rise., Elevation..ft., UAA..ft2.) %>% 
  rename(site = Site)
topo <- topo %>%
  mutate(type = replace(type, type == "Down", "Downstream"),
         type = replace(type, type == "head", "Head"),
         site = replace(site, site == "W600", "Wind"),
         site = replace(site, site == "W400", "Wind"),
         site = replace(site, site == "GC100", "Glac"),
         site = replace(site, site == "GC300", "Glac"),
         site = replace(site, site == "LS0", "Land"),
         site = replace(site, site == "LS180", "Land"))
#selecting sites, renaming one of the columns in the same function

#combine the datasets by Site and type
comb <- left_join(temps.water, topo, by = c("site", "type"))
```

Plot time
```{r}
#making plots
#Elevation vs distribution
elevators <- ggplot(data = comb, 
                    aes(x = fct_reorder(site, Elevation..ft.),
                        y = Value,
                        fill = type))+
  geom_boxplot()

elevator.ridge <- ggplot(data = comb,
                         aes(x = Value,
                             y = fct_reorder(site, Elevation..ft.),
                             fill = type))+
  geom_density_ridges2(mapping = aes(scale=1))+
  theme_classic()+
  theme(axis.title.y= element_blank(),
        axis.title.x=element_text(size = 17),
        axis.ticks.y=element_blank(),
        strip.text.y = element_text(angle = 180, hjust = 1),
        line = element_blank(),
        axis.text.x = element_text(size = 17),
        axis.text.y = element_text(size = 17))+
  scale_y_discrete(expand = c(0.001, 0))+
  scale_x_continuous(limits = c(8,20), expand = c(0.001, 0))+
  xlab("Temp (C)")

```

Air temp plots
```{r}
#Before I can plot airT stuff I need to get some kind of AirT data into my df
#comine datasets by time and shed
temps.water <- filter(temps, type == "air")

```

```{r}
#by AirT
elevators <- ggplot(data = comb, 
                    aes(x = fct_reorder(site, Elevation..ft.),
                        y = Value,
                        fill = type))+
  geom_boxplot()

elevator.ridge <- ggplot(data = comb,
                         aes(x = Value,
                             y = site,
                             fill = type))+
  geom_density_ridges2(mapping = aes(scale=1))+
  theme_classic()+
  theme(axis.title.y=element_blank(),
        axis.title.x=element_text(size = 17),
        axis.ticks.y=element_blank(),
        strip.text.y = element_text(angle = 180, hjust = 1),
        line = element_blank(),
        axis.text.x = element_text(size = 17),
        axis.text.y = element_text(size = 17))+
  scale_y_discrete(expand = c(0.001, 0))+
  scale_x_continuous(limits = c(8,20), expand = c(0.001, 0))+
  xlab("Temp (C)")
```

